process.env.NODE_ENV = process.env.NODE_ENV || 'test'
process.env.TZ = process.env.TZ || 'UTC'
process.env.PORT = process.env.PORT || '0'
process.env.APP_BASE_URL = process.env.APP_BASE_URL || 'http://localhost:4000'
process.env.FRONTEND_URL = process.env.FRONTEND_URL || 'http://localhost:5173'
process.env.CORS_ORIGIN = process.env.CORS_ORIGIN || 'http://localhost:5173'
process.env.JWT_ACCESS_SECRET = process.env.JWT_ACCESS_SECRET || 'test-access-secret'
process.env.JWT_REFRESH_SECRET = process.env.JWT_REFRESH_SECRET || 'test-refresh-secret'