export const MOROCCO_CITY_REGION_OPTIONS = [
  { city: 'Casablanca', region: 'Casablanca-Settat' },
  { city: 'Mohammedia', region: 'Casablanca-Settat' },
  { city: 'Settat', region: 'Casablanca-Settat' },
  { city: 'El Jadida', region: 'Casablanca-Settat' },
  { city: 'Berrechid', region: 'Casablanca-Settat' },
  { city: 'Rabat', region: 'Rabat-Salé-Kénitra' },
  { city: 'Salé', region: 'Rabat-Salé-Kénitra' },
  { city: 'Kénitra', region: 'Rabat-Salé-Kénitra' },
  { city: 'Témara', region: 'Rabat-Salé-Kénitra' },
  { city: 'Sidi Kacem', region: 'Rabat-Salé-Kénitra' },
  { city: 'Fès', region: 'Fès-Meknès' },
  { city: 'Meknès', region: 'Fès-Meknès' },
  { city: 'Taza', region: 'Fès-Meknès' },
  { city: 'Sefrou', region: 'Fès-Meknès' },
  { city: 'Ifrane', region: 'Fès-Meknès' },
  { city: 'Marrakech', region: 'Marrakech-Safi' },
  { city: 'Safi', region: 'Marrakech-Safi' },
  { city: 'Essaouira', region: 'Marrakech-Safi' },
  { city: 'El Kelaa des Sraghna', region: 'Marrakech-Safi' },
  { city: 'Tanger', region: 'Tanger-Tétouan-Al Hoceïma' },
  { city: 'Tétouan', region: 'Tanger-Tétouan-Al Hoceïma' },
  { city: 'Al Hoceïma', region: 'Tanger-Tétouan-Al Hoceïma' },
  { city: 'Larache', region: 'Tanger-Tétouan-Al Hoceïma' },
  { city: 'Chefchaouen', region: 'Tanger-Tétouan-Al Hoceïma' },
  { city: 'Agadir', region: 'Souss-Massa' },
  { city: 'Inezgane', region: 'Souss-Massa' },
  { city: 'Taroudant', region: 'Souss-Massa' },
  { city: 'Tiznit', region: 'Souss-Massa' },
  { city: 'Ouarzazate', region: 'Drâa-Tafilalet' },
  { city: 'Errachidia', region: 'Drâa-Tafilalet' },
  { city: 'Midelt', region: 'Drâa-Tafilalet' },
  { city: 'Zagora', region: 'Drâa-Tafilalet' },
  { city: 'Oujda', region: "L'Oriental" },
  { city: 'Nador', region: "L'Oriental" },
  { city: 'Berkane', region: "L'Oriental" },
  { city: 'Taourirt', region: "L'Oriental" },
  { city: 'Béni Mellal', region: 'Béni Mellal-Khénifra' },
  { city: 'Khouribga', region: 'Béni Mellal-Khénifra' },
  { city: 'Fkih Ben صالح', region: 'Béni Mellal-Khénifra' },
  { city: 'Laâyoune', region: 'Laâyoune-Sakia El Hamra' },
  { city: 'Boujdour', region: 'Laâyoune-Sakia El Hamra' },
  { city: 'Dakhla', region: 'Dakhla-Oued Ed-Dahab' },
  { city: 'Aousserd', region: 'Dakhla-Oued Ed-Dahab' },
  { city: 'Guelmim', region: 'Guelmim-Oued Noun' },
  { city: 'Tan-Tan', region: 'Guelmim-Oued Noun' },
];

export const MOROCCO_CITY_SELECT_OPTIONS = MOROCCO_CITY_REGION_OPTIONS.map((entry) => ({
  value: entry.city,
  label: `${entry.city} (${entry.region})`,
}));
